In [1]:
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data.dataloader import DataLoader
from torchvision.datasets import ImageFolder
from torchvision.transforms import ToTensor
import torchvision
import os
import numpy as np
import matplotlib.pyplot as plt
from torchvision import transforms
import time
from tqdm import tqdm
from sklearn.metrics import confusion_matrix
#from models import * #model and dataset
from train import *

if torch.cuda.is_available():  
    torch.cuda.empty_cache()
    device = "cuda:0" 
else:  
    device = "cpu" 
    
print(torch.__version__)

c:\Users\jerry\anaconda3\envs\PyTorch\lib\site-packages\tqdm\auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


1.10.2


In [2]:
torch.manual_seed(16)
imgpath = 'Cropped_All'

dataset = Polyp_or_Not(imgpath)
batch = 8

sz = len(dataset)
trlen = int(len(dataset)*0.8)
vllen = sz - trlen
trainset, validset = torch.utils.data.random_split(dataset,[trlen,vllen])

train_loader=DataLoader(trainset,batch,shuffle=True)
valid_loader = DataLoader(validset,batch,shuffle=True)

model = encoder(n_classes = 2).to(device)
epochs = 15

optimizer = optim.Adadelta(model.parameters(), lr=0.0001)
loss_function = nn.CrossEntropyLoss()

for epoch in range(epochs):
    tg = []
    pd = []
    train_accuracy=0.0
    test_accuracy=0.0
    model.train()
    for data, target in tqdm(train_loader):
        data,target=data.to(device),target.to(device)
        optimizer.zero_grad()
        output=model(data.float())
        loss=loss_function(output,target)
        loss.backward()
        optimizer.step()
        _,prediction=torch.max(output.data,1)
        train_accuracy+=int(torch.sum(prediction==target.data))
    train_accuracy=train_accuracy/trlen 
    model.eval()
    
    with torch.no_grad():
        for data, target in tqdm(valid_loader):
            data,target=data.to(device),target.to(device)
            output=model(data.float())
            _,prediction=torch.max(output.data,1)
            test_accuracy+=int(torch.sum(prediction==target.data))
            for k in prediction:
                pd.append(k.item())
            for l in target.data:
                tg.append(l.item())
    torch.save(model,'encoder.pt')
    test_accuracy=test_accuracy/vllen
    print('epoch '+str(epoch+1)+' train acurracy: '+str(train_accuracy)+' test accuracy: '+str(test_accuracy))
    print(confusion_matrix(tg,pd))

100%|██████████| 4/4 [00:00<00:00, 26.49it/s]


epoch 1 train acurracy: 0.47572815533980584 test accuracy: 0.6153846153846154
[[ 0 10]
 [ 0 16]]


100%|██████████| 4/4 [00:00<00:00, 27.21it/s]


epoch 2 train acurracy: 0.5242718446601942 test accuracy: 0.38461538461538464
[[ 9  1]
 [15  1]]


100%|██████████| 4/4 [00:00<00:00, 26.85it/s]


epoch 3 train acurracy: 0.5728155339805825 test accuracy: 0.3076923076923077
[[ 5  5]
 [13  3]]


100%|██████████| 4/4 [00:00<00:00, 27.78it/s]


epoch 4 train acurracy: 0.6019417475728155 test accuracy: 0.5769230769230769
[[ 4  6]
 [ 5 11]]


100%|██████████| 4/4 [00:00<00:00, 27.78it/s]


epoch 5 train acurracy: 0.6019417475728155 test accuracy: 0.5
[[4 6]
 [7 9]]


100%|██████████| 4/4 [00:00<00:00, 25.32it/s]


epoch 6 train acurracy: 0.6310679611650486 test accuracy: 0.5384615384615384
[[5 5]
 [7 9]]


100%|██████████| 4/4 [00:00<00:00, 26.50it/s]


epoch 7 train acurracy: 0.6699029126213593 test accuracy: 0.5384615384615384
[[5 5]
 [7 9]]


100%|██████████| 4/4 [00:00<00:00, 27.40it/s]


epoch 8 train acurracy: 0.6893203883495146 test accuracy: 0.46153846153846156
[[5 5]
 [9 7]]


100%|██████████| 4/4 [00:00<00:00, 26.49it/s]


epoch 9 train acurracy: 0.6796116504854369 test accuracy: 0.5
[[5 5]
 [8 8]]


100%|██████████| 4/4 [00:00<00:00, 28.17it/s]


epoch 10 train acurracy: 0.7864077669902912 test accuracy: 0.5769230769230769
[[6 4]
 [7 9]]


100%|██████████| 4/4 [00:00<00:00, 27.03it/s]


epoch 11 train acurracy: 0.7475728155339806 test accuracy: 0.5769230769230769
[[6 4]
 [7 9]]


100%|██████████| 4/4 [00:00<00:00, 27.03it/s]


epoch 12 train acurracy: 0.7378640776699029 test accuracy: 0.6153846153846154
[[ 6  4]
 [ 6 10]]


100%|██████████| 4/4 [00:00<00:00, 27.58it/s]


epoch 13 train acurracy: 0.7572815533980582 test accuracy: 0.6538461538461539
[[ 6  4]
 [ 5 11]]


100%|██████████| 4/4 [00:00<00:00, 26.77it/s]


epoch 14 train acurracy: 0.8349514563106796 test accuracy: 0.6153846153846154
[[ 6  4]
 [ 6 10]]


100%|██████████| 4/4 [00:00<00:00, 26.14it/s]


epoch 15 train acurracy: 0.8252427184466019 test accuracy: 0.6538461538461539
[[ 6  4]
 [ 5 11]]


In [3]:
print(output,target)

tensor([[-0.1407,  0.3019],
        [ 0.1097,  0.3179]], device='cuda:0') tensor([1, 1], device='cuda:0')
