In [1]:
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data.dataloader import DataLoader
from torchvision.datasets import ImageFolder
from torchvision.transforms import ToTensor
import torchvision
import os
import numpy as np
import matplotlib.pyplot as plt
from torchvision import transforms
import time
from tqdm import tqdm
from sklearn.metrics import confusion_matrix
#from models import * #model and dataset
from train import *

if torch.cuda.is_available():  
    torch.cuda.empty_cache()
    device = "cuda:0" 
else:  
    device = "cpu" 
    
print(torch.__version__)

c:\Users\jerry\anaconda3\envs\PyTorch\lib\site-packages\tqdm\auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


1.10.2


In [2]:
torch.manual_seed(186)
imgpath = 'Cropped_All'

dataset = Polyp_or_Not(imgpath)
batch = 8

sz = len(dataset)
trlen = int(len(dataset)*0.8)
vllen = sz - trlen
trainset, validset = torch.utils.data.random_split(dataset,[trlen,vllen])

train_loader=DataLoader(trainset,batch,shuffle=True)
valid_loader = DataLoader(validset,batch,shuffle=True)

model = VGG().to(device)
epochs = 25

optimizer = optim.Adadelta(model.parameters(), lr=0.001)
loss_function = nn.CrossEntropyLoss()

for epoch in range(epochs):
    tg = []
    pd = []
    train_accuracy=0.0
    test_accuracy=0.0
    model.train()
    for data, target in tqdm(train_loader):
        data,target=data.to(device),target.to(device)
        optimizer.zero_grad()
        output=model(data.float())
        loss=loss_function(output,target)
        loss.backward()
        optimizer.step()
        _,prediction=torch.max(output.data,1)
        train_accuracy+=int(torch.sum(prediction==target.data))
    train_accuracy=train_accuracy/trlen 
    model.eval()
    
    with torch.no_grad():
        for data, target in tqdm(valid_loader):
            data,target=data.to(device),target.to(device)
            output=model(data.float())
            _,prediction=torch.max(output.data,1)
            test_accuracy+=int(torch.sum(prediction==target.data))
            for k in prediction:
                pd.append(k.item())
            for l in target.data:
                tg.append(l.item())
    torch.save(model,'VGG.pt')
    test_accuracy=test_accuracy/vllen
    print('epoch '+str(epoch+1)+' train acurracy: '+str(train_accuracy)+' test accuracy: '+str(test_accuracy))
    print(confusion_matrix(tg,pd))

100%|██████████| 4/4 [00:00<00:00, 17.78it/s]


epoch 1 train acurracy: 0.5145631067961165 test accuracy: 0.5
[[6 7]
 [6 7]]


100%|██████████| 4/4 [00:00<00:00, 17.86it/s]


epoch 2 train acurracy: 0.49514563106796117 test accuracy: 0.46153846153846156
[[5 8]
 [6 7]]


100%|██████████| 4/4 [00:00<00:00, 16.67it/s]


epoch 3 train acurracy: 0.5728155339805825 test accuracy: 0.5
[[7 6]
 [7 6]]


100%|██████████| 4/4 [00:00<00:00, 17.17it/s]


epoch 4 train acurracy: 0.5728155339805825 test accuracy: 0.5769230769230769
[[6 7]
 [4 9]]


100%|██████████| 4/4 [00:00<00:00, 17.70it/s]


epoch 5 train acurracy: 0.5631067961165048 test accuracy: 0.5
[[6 7]
 [6 7]]


100%|██████████| 4/4 [00:00<00:00, 16.33it/s]


epoch 6 train acurracy: 0.6116504854368932 test accuracy: 0.5
[[6 7]
 [6 7]]


100%|██████████| 4/4 [00:00<00:00, 17.78it/s]


epoch 7 train acurracy: 0.5825242718446602 test accuracy: 0.46153846153846156
[[4 9]
 [5 8]]


100%|██████████| 4/4 [00:00<00:00, 17.80it/s]


epoch 8 train acurracy: 0.6601941747572816 test accuracy: 0.46153846153846156
[[4 9]
 [5 8]]


100%|██████████| 4/4 [00:00<00:00, 17.47it/s]


epoch 9 train acurracy: 0.6699029126213593 test accuracy: 0.5769230769230769
[[7 6]
 [5 8]]


100%|██████████| 4/4 [00:00<00:00, 17.96it/s]


epoch 10 train acurracy: 0.7184466019417476 test accuracy: 0.5769230769230769
[[7 6]
 [5 8]]


100%|██████████| 4/4 [00:00<00:00, 17.70it/s]


epoch 11 train acurracy: 0.6990291262135923 test accuracy: 0.5769230769230769
[[7 6]
 [5 8]]


100%|██████████| 4/4 [00:00<00:00, 17.94it/s]


epoch 12 train acurracy: 0.6796116504854369 test accuracy: 0.5384615384615384
[[5 8]
 [4 9]]


100%|██████████| 4/4 [00:00<00:00, 17.78it/s]


epoch 13 train acurracy: 0.7572815533980582 test accuracy: 0.5769230769230769
[[8 5]
 [6 7]]


100%|██████████| 4/4 [00:00<00:00, 17.94it/s]


epoch 14 train acurracy: 0.8155339805825242 test accuracy: 0.5384615384615384
[[6 7]
 [5 8]]


100%|██████████| 4/4 [00:00<00:00, 17.54it/s]


epoch 15 train acurracy: 0.7378640776699029 test accuracy: 0.5384615384615384
[[6 7]
 [5 8]]


100%|██████████| 4/4 [00:00<00:00, 16.95it/s]


epoch 16 train acurracy: 0.7961165048543689 test accuracy: 0.5384615384615384
[[6 7]
 [5 8]]


100%|██████████| 4/4 [00:00<00:00, 16.95it/s]


epoch 17 train acurracy: 0.8349514563106796 test accuracy: 0.5384615384615384
[[6 7]
 [5 8]]


100%|██████████| 4/4 [00:00<00:00, 17.02it/s]


epoch 18 train acurracy: 0.7378640776699029 test accuracy: 0.5
[[6 7]
 [6 7]]


100%|██████████| 4/4 [00:00<00:00, 18.03it/s]


epoch 19 train acurracy: 0.8058252427184466 test accuracy: 0.5384615384615384
[[6 7]
 [5 8]]


100%|██████████| 4/4 [00:00<00:00, 16.81it/s]


epoch 20 train acurracy: 0.8932038834951457 test accuracy: 0.5769230769230769
[[6 7]
 [4 9]]


100%|██████████| 4/4 [00:00<00:00, 17.78it/s]


epoch 21 train acurracy: 0.8543689320388349 test accuracy: 0.5384615384615384
[[7 6]
 [6 7]]


100%|██████████| 4/4 [00:00<00:00, 17.62it/s]


epoch 22 train acurracy: 0.8543689320388349 test accuracy: 0.5769230769230769
[[7 6]
 [5 8]]


100%|██████████| 4/4 [00:00<00:00, 16.48it/s]


epoch 23 train acurracy: 0.8737864077669902 test accuracy: 0.6153846153846154
[[7 6]
 [4 9]]


100%|██████████| 4/4 [00:00<00:00, 17.32it/s]


epoch 24 train acurracy: 0.9223300970873787 test accuracy: 0.6153846153846154
[[7 6]
 [4 9]]


100%|██████████| 4/4 [00:00<00:00, 17.47it/s]


epoch 25 train acurracy: 0.9029126213592233 test accuracy: 0.5384615384615384
[[7 6]
 [6 7]]


In [3]:
print(output,target)

tensor([[-0.2439,  0.0033],
        [ 0.2530, -1.3514]], device='cuda:0') tensor([0, 0], device='cuda:0')
